# Generated by Django 5.2 on 2025-04-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_transaction_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=150, max_digits=10, null=True),
        ),
    ]
